#!/usr/bin/env python3
"""Generate a synthetic flight log for trying Sundial out.

Writes an OpenRocket-flavoured CSV: a commented preamble, a commented header
row, units in the column names, and a string state column that Sundial turns
into timeline events.

    python3 examples/make_demo_log.py > examples/demo-flight.csv
"""

import math
import random
import sys

RATE = 50          # control-loop Hz
DURATION = 92.0    # seconds

T_LAUNCH, T_BURNOUT = 5.0, 8.2
T_APOGEE, T_DROGUE = 24.6, 25.2
T_MAIN, T_LAND = 62.0, 88.4

COLUMNS = [
    "Time (s)", "state", "altitude (m)", "velocity (m/s)",
    "accel_x (m/s^2)", "accel_y (m/s^2)", "accel_z (m/s^2)",
    "gyro_x (deg/s)", "gyro_y (deg/s)", "gyro_z (deg/s)",
    "pressure (Pa)", "temperature (C)", "battery (V)",
    "gps_lat (deg)", "gps_lon (deg)", "gps_sats", "rssi (dBm)",
    "mach", "pyro_drogue", "pyro_main",
]


def state_at(t: float) -> str:
    if t < T_LAUNCH:
        return "PAD"
    if t < T_BURNOUT:
        return "BOOST"
    if t < T_DROGUE:
        return "COAST"
    if t < T_MAIN:
        return "DROGUE"
    if t < T_LAND:
        return "MAIN"
    return "LANDED"


def main() -> None:
    rnd = random.Random(20260913)
    out = sys.stdout

    out.write("# Sundial demo flight log\n")
    out.write("# Synthetic L1850 two-stage-recovery profile, 50 Hz control loop\n")
    out.write("# Generated by examples/make_demo_log.py\n")
    out.write("# " + ",".join(COLUMNS) + "\n")

    alt = vel = 0.0
    dt = 1.0 / RATE
    n = int(RATE * DURATION)

    for i in range(n):
        t = i * dt

        if t < T_LAUNCH:
            accel, vel, alt = 0.0, 0.0, 0.0
        elif t < T_BURNOUT:
            burn = (t - T_LAUNCH) / (T_BURNOUT - T_LAUNCH)
            accel = 92.0 * (1 - 0.45 * burn) - 9.81
        elif t < T_APOGEE:
            accel = -9.81 - 0.00018 * vel * abs(vel)
        elif t < T_DROGUE:
            accel = -9.81
        elif t < T_MAIN:
            accel = (-24.0 - vel) * 1.6
        elif t < T_LAND:
            accel = (-6.4 - vel) * 1.1
        else:
            accel, vel = 0.0, 0.0

        if T_LAUNCH <= t < T_LAND:
            vel += accel * dt
            alt += vel * dt
            if alt < 0:
                alt, vel = 0.0, 0.0

        boosting = T_LAUNCH < t < T_BURNOUT
        jitter = 1.4 if T_LAUNCH < t < T_APOGEE else 0.25
        spin = 0.0 if t < T_LAUNCH else (40.0 * (t - T_LAUNCH) if t < T_BURNOUT else 130.0)
        # Specific force: 1 g on the pad, ~0 in freefall.
        a_z = (9.81 if t < T_LAUNCH else
               accel + 9.81 if t < T_BURNOUT else
               0.4 if t < T_DROGUE else 8.8)

        row = [
            f"{t:.3f}",
            state_at(t),
            f"{alt + rnd.uniform(-0.5, 0.5) * jitter:.3f}",
            f"{vel + rnd.uniform(-0.5, 0.5) * jitter * 2:.3f}",
            f"{rnd.uniform(-0.5, 0.5) * (3.5 if boosting else 0.5):.3f}",
            f"{rnd.uniform(-0.5, 0.5) * (3.5 if boosting else 0.5):.3f}",
            f"{a_z + rnd.uniform(-0.5, 0.5) * (4 if boosting else 0.8):.3f}",
            f"{(8 * math.sin(t * 1.7) if t < T_DROGUE else 90 * math.sin(t * 2.3)) + rnd.uniform(-2.5, 2.5):.2f}",
            f"{(8 * math.cos(t * 1.9) if t < T_DROGUE else 90 * math.cos(t * 2.1)) + rnd.uniform(-2.5, 2.5):.2f}",
            f"{(spin if t < T_DROGUE else 220 * math.sin(t * 3.1)) + rnd.uniform(-3, 3):.2f}",
            f"{101325 * math.exp(-alt / 8434.0) + rnd.uniform(-11, 11):.1f}",
            f"{21.5 - alt * 0.0065 + rnd.uniform(-0.15, 0.15):.2f}",
            f"{8.31 - t * 0.0021 - (0.22 if boosting else 0) + rnd.uniform(-0.006, 0.006):.4f}",
            f"{32.94021 + alt * 1e-7 + rnd.uniform(-1e-6, 1e-6):.7f}",
            f"{-106.92198 + t * 1.4e-6 + rnd.uniform(-1e-6, 1e-6):.7f}",
            # GPS lock degrades under boost acceleration, as it does in reality.
            f"{11 if t < T_LAUNCH else (4 if t < T_BURNOUT else min(11, int(5 + (t - T_BURNOUT) * 0.4)))}",
            f"{-62 - alt * 0.011 + rnd.uniform(-1.75, 1.75):.1f}",
            f"{max(0.0, vel) / 330.0:.4f}",
            "1" if T_DROGUE <= t < T_DROGUE + 0.35 else "0",
            "1" if T_MAIN <= t < T_MAIN + 0.35 else "0",
        ]
        out.write(",".join(row) + "\n")


if __name__ == "__main__":
    main()
